version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/scruid

    environment:
      _JAVA_OPTIONS: -Xms512m -Xmx4g
      TERM: dumb

    steps:
      - checkout
      - run: ./services.sh start
      - run: cp build.sbt /tmp/build.sbt
      - restore_cache:
          key: ivy2-{{ checksum "/tmp/build.sbt" }}
      - run: wget localhost:8082/status
      - run: sbt ++2.11.12 compile
      - run: sbt ++2.12.9 compile
      - run: sbt ++2.13.1 compile
      - run: sbt coverage test coverageReport
      - run: docker-compose down
      - store_artifacts:
          path: target/scala-2.12/scoverage-report
      - save_cache:
          key: ivy2-{{ checksum "/tmp/build.sbt" }}
          paths:
            - ~/.ivy2
